services:
  - type: web
    name: samfkurator
    runtime: python
    buildCommand: pip install .
    startCommand: gunicorn samfkurator.web.app:app --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: "3.12"
